# Generated by Django 2.0.4 on 2018-04-26 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mechanism',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='mechanism',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mechanism',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
