# Generated by Django 2.0.4 on 2018-05-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180505_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanism',
            name='image',
            field=models.ImageField(default='img/mechanism-placeholder.png', upload_to='img/'),
        ),
    ]
