# Generated by Django 2.0.4 on 2018-07-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180611_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='parametric_model',
            field=models.FileField(blank=True, null=True, upload_to='parametric_models'),
        ),
    ]
