# Generated by Django 2.0.4 on 2018-07-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mechanism_parametric_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
