# Generated by Django 2.0.4 on 2018-08-11 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mechanism_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mechanism',
            options={'ordering': ('-rating_likes', 'rating_dislikes')},
        ),
        migrations.AddField(
            model_name='mechanism',
            name='transmission_guessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mechanism',
            name='transmission_inverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mechanism',
            name='transmission',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.RegexValidator(message='Invalid format. Valid formats are: 1, 1 - 2, 1:2, 1:2 - 1:3', regex='^((\\d+( - \\d+)?)|(\\d+:\\d+( - \\d+:\\d+)?))$')]),
            preserve_default=False,
        ),
    ]
