# Generated by Django 2.0.4 on 2018-08-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180811_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanism',
            name='parametric_model',
            field=models.FileField(blank=True, default='', upload_to='parametric_models'),
            preserve_default=False,
        ),
    ]
